data:extend({
	{
		type = "recipe",
		name = "nutrients-from-coconut-meat",
		icon = "__pelagos__/graphics/nutrients-from-coconut-meat.png",
		category = "organic",
		subgroup = "agriculture-processes",
		enabled = false,
		allow_productivity = true,
		order = "c[nutrients]-d[nutrients-from-coconut-meat]",
		energy_required = 4,
		ingredients = { { type = "item", name = "coconut-meat", amount = 2 } },
		results = { { type = "item", name = "nutrients", amount = 8 } },
		crafting_machine_tint = {
			primary = { r = 1.000, g = 1.000, b = 1.000, a = 1.000 },
			secondary = { r = 0.900, g = 0.900, b = 0.900, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-processing",
		icon = "__pelagos__/graphics/coconut-processing.png",
		category = "organic-or-hand-crafting",
		subgroup = "agriculture-processes",
		order = "a[seeds]-a[coconut-processing]",
		enabled = false,
		allow_productivity = true,
		energy_required = 1,
		ingredients = { { type = "item", name = "coconut", amount = 1 } },
		results = {
			{ type = "item", name = "coconut-seed", amount = 1, probability = 0.09 },
			{ type = "item", name = "coconut-meat", amount = 2 },
			{ type = "item", name = "coconut-husk", amount = 2 },
		},
		crafting_machine_tint = {
			primary = { r = 0.960, g = 0.870, b = 0.690, a = 1.000 },
			secondary = { r = 0.820, g = 0.620, b = 0.360, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-oil",
		category = "organic-or-chemistry",
		subgroup = "fluid-recipes",
		order = "a[fluid]-b[coconut-oil]",
		auto_recycle = false,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "coconut-meat", amount = 15 },
		},
		results = { { type = "fluid", name = "coconut-oil", amount = 10 } },
		allow_productivity = true,
		enabled = false,
		crafting_machine_tint = {
			primary = { r = 1.000, g = 0.940, b = 0.620, a = 1.000 },
			secondary = { r = 0.900, g = 0.780, b = 0.400, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-sealant",
		category = "organic-or-assembling",
		subgroup = "agriculture-processes",
		order = "a[advanced-intermediats]-b[coconut-sealant]",
		auto_recycle = false,
		energy_required = 8,
		ingredients = {
			{ type = "fluid", name = "coconut-oil", amount = 10 },
			{ type = "item", name = "coconut-husk", amount = 5 },
		},
		results = { { type = "item", name = "coconut-sealant", amount = 1 } },
		allow_productivity = true,
		enabled = false,
		crafting_machine_tint = {
			primary = { r = 0.750, g = 0.550, b = 0.350, a = 1.000 },
			secondary = { r = 0.500, g = 0.350, b = 0.200, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "pelagos-science-pack",
		category = "organic",
		subgroup = "science-pack",
		surface_conditions = {
			{
				property = "pressure",
				min = 1500,
				max = 1500,
			},
		},
		enabled = false,
		ingredients = {
			{ type = "item", name = "coconut-sealant", amount = 2 },
			{ type = "item", name = "fermentation-bacteria", amount = 3 },
			{ type = "item", name = "activated-carbon", amount = 1 },
			{ type = "item", name = "titanium-dust", amount = 1 },
		},
		energy_required = 4,
		results = { { type = "item", name = "pelagos-science-pack", amount = 1 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.5, g = 0.7, b = 0.3, a = 1.000 },
			secondary = { r = 0.7, g = 0.9, b = 0.6, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "fermentation-bacteria",
		category = "organic",
		surface_conditions = {
			{
				property = "pressure",
				min = 1500,
				max = 1500,
			},
		},
		subgroup = "agriculture-processes",
		order = "b[agriculture]-d[bacteria]-a[fermentation-bacteria]",
		enabled = false,
		allow_productivity = true,
		energy_required = 1,
		ingredients = {
			{ type = "item", name = "raw-fish", amount = 2 },
			{ type = "fluid", name = "coconut-oil", amount = 30 },
			{ type = "fluid", name = "methane", amount = 150 },
		},
		results = {
			{ type = "item", name = "fermentation-bacteria", amount = 1, probability = 0.1 },
			{ type = "item", name = "spoilage", amount = 5 },
		},
		main_product = "fermentation-bacteria",
		crafting_machine_tint = {
			primary = { r = 0.5, g = 0.7, b = 0.3, a = 1.000 },
			secondary = { r = 0.7, g = 0.9, b = 0.6, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "fermentation-bacteria-cultivation",
		icon = "__pelagos__/graphics/fermentation-bacteria-cultivation.png",
		category = "organic",
		surface_conditions = {
			{
				property = "pressure",
				min = 1500,
				max = 1500,
			},
		},
		subgroup = "agriculture-processes",
		order = "b[agriculture]-d[bacteria]-b[fermentation-bacteria-cultivation]",
		enabled = false,
		allow_productivity = true,
		reset_freshness_on_craft = true,
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "fermentation-bacteria", amount = 1 },
			{ type = "item", name = "raw-fish", amount = 1 },
		},
		results = {
			{ type = "item", name = "fermentation-bacteria", amount = 4 },
		},
		crafting_machine_tint = {
			primary = { r = 0.5, g = 0.7, b = 0.3, a = 1.000 },
			secondary = { r = 0.7, g = 0.9, b = 0.6, a = 1.000 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "ethanol",
		category = "organic",
		subgroup = "fluid-recipes",
		surface_conditions = {
			{
				property = "pressure",
				min = 1500,
				max = 1500,
			},
		},
		enabled = false,
		allow_productivity = true,
		reset_freshness_on_craft = true,
		energy_required = 6,
		ingredients = {
			{ type = "item", name = "fermentation-bacteria", amount = 5 },
			{ type = "item", name = "nutrients", amount = 20 },
			{ type = "fluid", name = "water", amount = 100 },
			{ type = "item", name = "activated-carbon", amount = 1 },
		},
		results = {
			{ type = "fluid", name = "ethanol", amount = 120 },
		},
		crafting_machine_tint = {
			primary = { r = 0.5, g = 0.8, b = 1.0, a = 1.000 },
			secondary = { r = 0.7, g = 0.9, b = 1.0, a = 1.000 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "degradation-module",
		enabled = false,
		ingredients = {
			{ type = "item", name = "electronic-circuit", amount = 5 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
		},
		energy_required = 15,
		results = { { type = "item", name = "degradation-module", amount = 1 } },
	},
	{
		type = "recipe",
		name = "degradation-module-2",
		enabled = false,
		ingredients = {
			{ type = "item", name = "degradation-module", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
			{ type = "item", name = "processing-unit", amount = 5 },
		},
		energy_required = 30,
		results = { { type = "item", name = "degradation-module-2", amount = 1 } },
	},
	{
		type = "recipe",
		name = "degradation-module-3",
		enabled = false,
		ingredients = {
			{ type = "item", name = "degradation-module-2", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
			{ type = "item", name = "processing-unit", amount = 5 },
			{ type = "item", name = "fermentation-bacteria", amount = 5 },
		},
		energy_required = 60,
		results = { { type = "item", name = "degradation-module-3", amount = 1 } },
	},
	{
		type = "recipe",
		name = "wood-spoiling",
		icon = "__pelagos__/graphics/rotting-wood.png",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 7,
		ingredients = {
			{ type = "item", name = "wood", amount = 5 },
		},
		results = {
			{ type = "item", name = "spoilage", amount = 50 },
		},
		crafting_machine_tint = {
			primary = { r = 0.2, g = 0.4, b = 0.2, a = 1.000 },
			secondary = { r = 0.4, g = 0.6, b = 0.3, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-husk-spoiling",
		icon = "__pelagos__/graphics/coconut-husk-spoiling.png",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 7,
		ingredients = {
			{ type = "item", name = "coconut-husk", amount = 5 },
		},
		results = {
			{ type = "item", name = "spoilage", amount = 30 },
		},
		crafting_machine_tint = {
			primary = { r = 0.2, g = 0.4, b = 0.2, a = 1.000 },
			secondary = { r = 0.4, g = 0.6, b = 0.3, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "poison-rocket",
		enabled = false,
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 1 },
			{ type = "item", name = "poison-capsule", amount = 1 },
			{ type = "item", name = "coconut-sealant", amount = 1 },
			{ type = "item", name = "explosives", amount = 1 },
		},
		results = { { type = "item", name = "poison-rocket", amount = 1 } },
	},
	{
		type = "recipe",
		name = "slowdown-rocket",
		enabled = false,
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 1 },
			{ type = "item", name = "slowdown-capsule", amount = 1 },
			{ type = "item", name = "coconut-sealant", amount = 1 },
			{ type = "item", name = "explosives", amount = 1 },
		},
		results = { { type = "item", name = "slowdown-rocket", amount = 1 } },
	},
	{
		type = "recipe",
		name = "calciner",
		category = "advanced-crafting",
		surface_conditions = {
			{
				property = "pressure",
				min = 1500,
				max = 1500,
			},
		},
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 40 },
			{ type = "item", name = "steel-plate", amount = 40 },
			{ type = "item", name = "iron-plate", amount = 15 },
			{ type = "item", name = "refined-concrete", amount = 30 },
			{ type = "item", name = "coconut-sealant", amount = 20 },
		},
		energy_required = 10,
		results = { { type = "item", name = "calciner", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-mining-drill",
		energy_required = 2,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 10 },
			{ type = "item", name = "iron-gear-wheel", amount = 5 },
			{ type = "item", name = "engine-unit", amount = 2 },
			{ type = "item", name = "coconut-sealant", amount = 6 },
		},
		results = { { type = "item", name = "diesel-mining-drill", amount = 1 } },
		enabled = false,
	},
	{

		type = "recipe",
		name = "diesel-inserter",
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 4 },
			{ type = "item", name = "engine-unit", amount = 1 },
			{ type = "item", name = "coconut-sealant", amount = 4 },
			{ type = "item", name = "burner-inserter", amount = 1 },
		},
		results = { { type = "item", name = "diesel-inserter", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-assembling-machine",
		enabled = false,
		ingredients = {
			{ type = "item", name = "steel-plate", amount = 5 },
			{ type = "item", name = "coconut-sealant", amount = 10 },
			{ type = "item", name = "iron-plate", amount = 15 },
			{ type = "item", name = "iron-gear-wheel", amount = 7 },
			{ type = "item", name = "engine-unit", amount = 1 },
		},
		results = { { type = "item", name = "diesel-assembling-machine", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-pump",
		enabled = false,
		ingredients = {
			{ type = "item", name = "engine-unit", amount = 2 },
			{ type = "item", name = "pipe", amount = 4 },
			{ type = "item", name = "coconut-sealant", amount = 2 },
		},
		results = { { type = "item", name = "diesel-pump", amount = 1 } },
	},
	{
		type = "recipe",
		name = "wooden-platform",
		enabled = false,
		ingredients = {
			{ type = "item", name = "wood", amount = 20 },
			{ type = "item", name = "coconut-sealant", amount = 10 },
			{ type = "item", name = "coconut-husk", amount = 10 },
		},
		results = { { type = "item", name = "wooden-platform", amount = 1 } },
	},
	{
		type = "recipe",
		name = "barreling-machine",
		enabled = false,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 10 },
			{ type = "item", name = "iron-gear-wheel", amount = 5 },
			{ type = "item", name = "electronic-circuit", amount = 1 },
		},
		results = { { type = "item", name = "barreling-machine", amount = 1 } },
	},
	{
		type = "recipe",
		name = "casting-engine-unit",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-h[casting-engine-unit]",
		icon = "__pelagos__/graphics/casting-engine-unit.png",
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "molten-iron", amount = 55, fluidbox_multiplier = 55 },
			{ type = "item", name = "activated-carbon", amount = 5 },
		},
		energy_required = 15,
		-- energy_required = 10, for assembling machine
		allow_decomposition = false,
		results = { { type = "item", name = "engine-unit", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "titanium-dust",
		category = "organic",
		subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 5,
		ingredients = {
			{ type = "fluid", name = "titanium-sludge", amount = 100 },
			{ type = "item", name = "fermentation-bacteria", amount = 4 },
		},
		results = {
			{ type = "item", name = "titanium-dust", amount = 1, probability = 0.2 },
			{ type = "item", name = "spoilage", amount = 10 },
		},
		crafting_machine_tint = {
			primary = { r = 0.2, g = 0.4, b = 0.2, a = 1.000 },
			secondary = { r = 0.4, g = 0.6, b = 0.3, a = 1.000 },
		},
		main_product = "titanium-dust",
	},
	{
		type = "recipe",
		name = "titanium-plate",
		--subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		category = "smelting",
		enabled = false,
		energy_required = 10,
		ingredients = { { type = "item", name = "titanium-dust", amount = 2 } },
		results = { { type = "item", name = "titanium-plate", amount = 1 } },
		allow_productivity = true,
	},

	{
		type = "recipe",
		name = "titanium-barrel",
		category = "crafting",
		energy_required = 1,
		subgroup = "intermediate-product",
		enabled = false,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 1 },
		},
		results = { { type = "item", name = "titanium-barrel", amount = 1 } },
		allow_productivity = true,
	},
})
--pelagos-rocket-part
data:extend({
	{
		type = "recipe",
		name = "pelagos-rocket-part",
		energy_required = 3,
		enabled = false,
		hide_from_player_crafting = true,
		auto_recycle = false,
		category = "rocket-building",
		ingredients = {
			{ type = "item", name = "processing-unit", amount = 1 },
			{ type = "item", name = "titanium-plate", amount = 1 },
			{ type = "fluid", name = "ethanol", amount = 100 },
		},
		surface_conditions = {
			{
				property = "pressure",
				min = 1500,
				max = 1500,
			},
		},
		results = { { type = "item", name = "rocket-part", amount = 1 } },
		allow_productivity = true,
	},
})

data:extend({
	{
		type = "recipe",
		name = "copper-biter-egg",
		category = "captive-spawner-process",
		order = "c[eggs]-a[copper-biter-egg]",
		hide_from_player_crafting = true,
		auto_recycle = false,
		preserve_products_in_machine_output = true,
		energy_required = 10,
		ingredients = {},
		results = {
			{ type = "item", name = "copper-biter-egg", amount = 5 },
		},
		enabled = false,
	},
	{
		type = "recipe",
		icon = "__pelagos__/graphics/copper-plate.png",
		name = "copper-plate-from-spitter-egg",
		category = "smelting",
		auto_recycle = false,
		energy_required = 3.2,
		ingredients = { { type = "item", name = "copper-biter-egg", amount = 1 } },
		results = { { type = "item", name = "copper-plate", amount = 1 } },
		allow_productivity = true,
	},
})
data:extend({
	{
		type = "recipe",
		name = "fermented-fish",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "coconut-meat", amount = 5 },
			{ type = "item", name = "raw-fish", amount = 15 },
			{ type = "item", name = "fermentation-bacteria", amount = 5 },
		},
		results = {
			{ type = "item", name = "fermented-fish", amount = 5 },
		},
		crafting_machine_tint = {
			primary = { r = 0.2, g = 0.6, b = 0.2, a = 1.000 },
			secondary = { r = 0.4, g = 0.8, b = 0.3, a = 1.000 },
		},
	},
})
